apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    io.kompose.service: flower
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flower
    spec:
      containers:
        - args:
            - flower
          env:
            - name: EXECUTOR
              value: SparkRun
            - name: REDIS_PASSWORD
              value: redispass
          image: " "
          name: flower
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - flower
        from:
          kind: DockerImage
          name: flower:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
