apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    io.kompose.service: webserver
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: EXECUTOR
              value: SparkRun
            - name: FERNET_KEY
              value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - name: LOAD_EX
              value: "n"
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_USER
              value: airflow
            - name: REDIS_PASSWORD
              value: redispass
          image: ' '
          name: webserver
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: webserver-claim0
            - mountPath: /usr/local/airflow/plugins
              name: webserver-claim1
            - mountPath: /usr/local/airflow/spark_scripts
              name: webserver-claim2
            - mountPath: /usr/local/airflow/downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: webserver-claim0
          persistentVolumeClaim:
            claimName: webserver-claim0
        - name: webserver-claim1
          persistentVolumeClaim:
            claimName: webserver-claim1
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - webserver
        from:
          kind: ImageStreamTag
          name: webserver:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
