apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  # selector:
  #   io.kompose.service: worker
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - worker
          env:
            - name: EXECUTOR
              value: SparkRun
            - name: FERNET_KEY
              value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_USER
              value: airflow
            - name: REDIS_PASSWORD
              value: redispass
          image: " "
          name: worker
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: worker-claim0
            - mountPath: /var/run/docker.sock
              name: worker-claim1
            - mountPath: /usr/local/airflow/plugins
              name: worker-claim2
            - mountPath: /usr/local/airflow/spark_scripts
              name: worker-claim3
            - mountPath: /usr/local/airflow/downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: worker-claim0
          persistentVolumeClaim:
            claimName: worker-claim0
        - name: worker-claim1
          persistentVolumeClaim:
            claimName: worker-claim1
        - name: worker-claim2
          persistentVolumeClaim:
            claimName: worker-claim2
        - name: worker-claim3
          persistentVolumeClaim:
            claimName: worker-claim3
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - worker
        from:
          kind: DockerImage
          name: worker:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
